# fly.toml app configuration file generated for spazio-alfieri-bot on 2024-09-27T00:40:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spazio-alfieri-bot'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health_check]
    interval = '30s'
    timeout = '2s'
    grace_period = '30s'
    method = "GET"
    path = "/health"
    type = "http"
    port = 3000

[[vm]]
  size = 'shared-cpu-1x'
